/*
* Controller	: EnquiryDTOService
* Purpose		: This is a Web service controller. It is used for adding or updating pricing of FG and its variants.
Prices coming from SAP to SF
* Created Date	: 18-Nov-2021
-------------------------------------------------------
#ModificationDate	: Details
15-Dec-2021			: To update the error message response.
*/
@RestResource(urlMapping='/EnquiryDTOService/*')
global class EnquiryDTOService {
@HttpPost
    global static void doPost(){
        
    }
}